=== tejasshah2k19/xml-hariom/mail.dtd
<!ELEMENT mail (to+,date,from,subject?,body?,attachment*)>
<!ELEMENT to (#PCDATA) >
<!ELEMENT date (#DATE) >
<!ELEMENT from (#PCDATA) >
<!ELEMENT subject (#PCDATA) >
<!ELEMENT body (#PCDATA) >
<!ELEMENT attachment (name,size) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>

<!-- this is commnet  same as html xml -->

=== tejasshah2k19/xml-hariom/mail.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE mail SYSTEM "mail.dtd">
<mail>
    <to>abc1@gmail.com</to>
    <to>abc2@gmail.com</to>
    <to>abc3@gmail.com</to>
    <from>xyz@gmail.com</from>
    <subject>Well Wishesh</subject>
    <body>Good Morning</body>
    <signature>Xyz</signature>
    <attachment type="pdf">
        <name>well.pdf</name>
        <size>1mb</size>
    </attachment>
</mail>
